name: Wheel Builder
on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  manylinux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux1_x86_64
    strategy:
      matrix:
        PYTHON: ["cp35-cp35m"]
    name: "Python ${{ matrix.PYTHON }} for manylinux1"
    steps:
      - run: ls /opt/python/
      - run: /opt/python/${{ matrix.PYTHON }}/bin/python -m pip install virtualenv
      - run: /opt/python/${{ matrix.PYTHON }}/bin/python -m virtualenv .venv
      - name: Install python dependencies
        run: .venv/bin/pip install -U pip cffi
      - run: curl -L https://github.com/nthparty/rbcl/archive/refs/heads/master.zip --output rbcl-${{ github.event.inputs.version }}.zip && unzip rbcl*.zip && mkdir tmpwheelhouse

      - run: |
          REGEX="cp3([0-9])*"
          if [[ "${{ matrix.PYTHON }}" =~ $REGEX ]]; then
              PY_LIMITED_API="--py-limited-api=cp3${BASH_REMATCH[1]}"
          fi
          cd rbcl-master
          rm -f dist/*.*
          LIBSODIUM_MAKE_ARGS="-j$(nproc)" ../.venv/bin/python setup.py bdist_wheel $PY_LIMITED_API && mv dist/rbcl*.whl ../tmpwheelhouse
      - run: ls ..; ls .; auditwheel repair tmpwheelhouse/rbcl-${{ github.event.inputs.version }}-cp35-abi3-linux_x86_64.whl -w wheelhouse/
      - run: .venv/bin/pip install rbcl --no-index -f wheelhouse/
      - run: |
          .venv/bin/python -c "import rbcl.bindings as lib; print(lib.crypto_core_ristretto255_is_valid_point(lib.crypto_core_ristretto255_random()))"
      - run: mkdir rbcl-wheelhouse
      - run: mv wheelhouse/rbcl*.whl rbcl-wheelhouse/
      - uses: actions/upload-artifact@v1
        with:
          name: "rbcl-${{ github.event.inputs.version }}-manylinux1-${{ matrix.PYTHON }}"
          path: rbcl-wheelhouse/
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        PYTHON:
          - VERSION: '3.8'
            ABI_VERSION: '3.5'
            DOWNLOAD_URL: 'https://www.python.org/ftp/python/3.8.2/python-3.8.2-macosx10.9.pkg'
            BIN_PATH: '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3'
    name: "Python ${{ matrix.PYTHON.VERSION }} for ABI ${{ matrix.PYTHON.ABI_VERSION }} on macOS"
    steps:
      - uses: actions/checkout@master
      - run: |
          curl "$PYTHON_DOWNLOAD_URL" -o python.pkg
          sudo installer -pkg python.pkg -target /
        env:
          PYTHON_DOWNLOAD_URL: ${{ matrix.PYTHON.DOWNLOAD_URL }}
      - run: ${{ matrix.PYTHON.BIN_PATH }} -m pip install -U virtualenv
      - run: ${{ matrix.PYTHON.BIN_PATH }} -m virtualenv venv
      - run: venv/bin/pip install -U pip wheel cffi
      - run: curl -L https://github.com/nthparty/rbcl/archive/refs/heads/master.zip --output rbcl-${{ github.event.inputs.version }}.zip && unzip rbcl*.zip && mkdir wheelhouse
      - name: Build the wheel
        run: |
            REGEX="3\.([0-9])*"
            if [[ "$PYTHON_VERSION" =~ $REGEX ]]; then
                PY_LIMITED_API="--py-limited-api=cp3${BASH_REMATCH[1]}"
            fi

            cd rbcl-master
            rm -f dist/*.*
            LIBSODIUM_MAKE_ARGS="-j$(sysctl -n hw.ncpu)" CFLAGS="-mmacosx-version-min=10.9 -march=core2" \
                ../venv/bin/python setup.py bdist_wheel $PY_LIMITED_API && mv dist/rbcl*.whl ../wheelhouse
            cd ..
        env:
          PYTHON_VERSION: ${{ matrix.PYTHON.ABI_VERSION }}
      - run: venv/bin/pip install -f wheelhouse --no-index rbcl
      - run: |
          venv/bin/python -c "import rbcl.bindings as lib; print(lib.crypto_core_ristretto255_is_valid_point(lib.crypto_core_ristretto255_random()))"

      - run: mkdir rbcl-wheelhouse
      - run: mv wheelhouse/rbcl*.whl rbcl-wheelhouse/
      - uses: actions/upload-artifact@v1
        with:
          name: "rbcl-${{ github.event.inputs.version }}-macOS-${{ matrix.PYTHON.VERSION }}"
          path: rbcl-wheelhouse/
